dist: trusty
sudo: required
language: node_js
node_js:
- 9.4.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - SLACK_TEAM=T29E48P34
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: 5e5EoOVbE116gJFdZo7QqRfgbDiOQpDBNohdXj5OBoOSJVTIOALIgOO4H/xkUDoda4JUBOhyr8R4NbI5IWiL5GuHqYhRmmihFfTrJcwxFB8StDIu6v+YhKO9W97DuEC1DcJazRbrIBEDFK2s9GvH8mcaEU2P8rLdvTQOFwcEUWQqo9BnTRiZSbk216a3RN9eGGYblu0Qmx5lr2m+2OABAkDbf+i92BlNWhgNPFNii1RzO++/dnMVD/Oudd1nMim5JlF0b627gtGIoHqWFSWSyXOEg5w1OLgj45uBGGXOrUTDE3PVpBY3Bp1/M92O8ojTYIXO6BxjZGrr5/wLgJXEvqoK3hB0xpcbTJT9oI7enB2LRiBCpNdFVsIw2672k3UPvkazeuW2BVUKZJpvUu5wBxsJvTNcznk5TuFpzW3AF24evtptNRgdfLMGueeDGfug5r6MxfC2NWPb3lcYZ+avcISbr7d17or5Wo8FYcC+TzKBLc6ztFLIAqDZOBBn4/txjOUJVpVOfJ7hJSos5obPPJNPYuFA9ctyBYQDnujMV5mIhNwoxantHXD3QvNip8REK+eu9oIc2YHIzGiIdMwEXq0J0itBHiPoVRJMwvqyJPKpMuRRc3PNJe1ngr8WHJDYTqIXWeVMNVNRxfJs6ZAjaRTZjWO0xJ2qPHyijkgRPtw=
  - DOCKER_REGISTRY=atomist
  - secure: VIDAqWMuqz4+TX8vtVz/blAU61Iw3Dd8wCgXTNEYjQahqd4mNlr6dGBA0Hri3EkVnBSf1AH4OwzkE48IOpr2+iGMfXTKIvhc5LGBhkuXl9zjBVik/T5weReHlVweYokrtvhZsa2wullnk5dHn/PxVOvqzqPm2v1ezVhkp6KlMW3b8rl3Q3vhsKlc6F3kjpdkah4kfOZ3RL7hB0TvUF09CDnciiIpohlvTPwAQWQ/elirD1rJo/SDpZXPCQR+DuffN0WvG/KUS9NNn5wr/kX5eETtf4/AfmwIwXs++MsCrQUiMQp/PPTjcNn8/lNDzvZw6BvszMiu4ynCWB8yhqvLUgnyPtTS2hkhdE7Pt91p5djSAmkVbm8TmdgUiXkXUGLG4Mhm70fSlidc9cLoy4/ptjDp1F4uhUJBgW+vYR7aVOusY1eASSz2iRDLVS3LUc6uxD2o3/RQ7DLV++E6oG7ubdkXy907qEZkDr1FzgXkeiIaU6gr1T1n3cyTNSTZpohEoSQAYCnGYQmVX936S6KDfN62IQc36V3BPBK3I4gEbfq6A3V+lSjRKQ+UgfBrfDF7OY/jrNlEDFIFh2Bg8cUcLH6m5so6dhOhPhGe+XzY8jMAcSAM/n7bVIE7CGuucgsveAxxEbPUiVTEu/8+lmN+9owFXuo6kK28wt2zrOiaMro=
  - secure: sIJP4pJuAXqofCZ/o4BvBnjtQzG/oi9WK8C4t8vEOHKflDSbh/0+h6l2qvFl0cRrTaMM4LY0MR0fUakU7IT79l8L4LMnEyNMu12YTvHYaJfddsGJ9wVFk33d7k91/R3MGeluvewQOcsvSwjcq7auW0zItRTMMuYXiCUYKoDMEloMF642o+C04HIK/ZJbHEhpUAopRZDuRZTU227qVW51xxz2jutI/GjDXpe5hMv0/mxCx9+5+OhBPlFTK086eHBdfjofMlX1dmFntybd/S/YXUrEVDfGey3EL8WK/+HIUc4osUIGfu/nH8YY++GQGg/fPqaofxsXylOrxlEpwHXpFpjb/Ub535ZxjfhOHsSAPuYPS+f8IqiSAexeVCVj9yGHSN1qbp8nUkO84PbzuacYMb0NGs4VB4AQmTCJDMcfKHjLqiyqalaNjvI9ZM4gF128ExdfSqEXoA/K9/BQRACXnFeekBOq2G6w1Q9wZ6BA5+wvoKx8soycJ8w1cpWA5MbJp3V1tKZBMxu2HKvRQ3xINJYf+cLzZliVWId8qix+zR/tLtGI7hGW4GnZr1KBqpvL4FAxFhpj4IBr59+O/fXYba3aqosiKTDdRfTTG2QPjwUHrACMxvXRnx1tf1uL9dIfM/utxsaJ6icQq1UmNMDWu0n/Z1JUC1JA72MxpoGh4FI=
before_install:
- openssl aes-256-cbc -K $encrypted_bab9b497981d_key -iv $encrypted_bab9b497981d_iv
  -in .npmrc.enc -out .npmrc -d
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/$SLACK_TEAM"
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.m2"
before_deploy:
- touch build/typedoc/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
